#!/usr/bin/env python3
"""
gen_dafny_test.py
Generates data.dfy — the dataset used by the static KMeansTest.dfy harness.

Usage:
  python gen_dafny_test.py <k> <max_iter> [options]

Arguments:
  k               Number of clusters (also passed to make_blobs as centers=k)
  max_iter        Maximum kmeans iterations

Data generation options (all optional):
  --n-samples N       Number of points to generate        (default: 100)
  --n-features N      Number of dimensions per point      (default: 2)
  --center-box LO HI  Bounding box for cluster centers    (default: -10 10)
  --cluster-std S     Standard deviation of each cluster  (default: 1.0)
  --random-state N    Random seed for reproducibility     (default: 0)

Output options:
  --output FILE       Output .dfy filename                (default: data.dfy)

Example:
  python gen_dafny_test.py 3 100 --n-samples 50 --n-features 4 --random-state 42

Then run:
  dafny run KMeansTest.dfy --allow-warnings
"""

import sys
import argparse


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("k", type=int, help="Number of clusters")
    p.add_argument("max_iter", type=int, help="Maximum kmeans iterations")
    p.add_argument("--n-samples",    type=int,   default=100,   metavar="N")
    p.add_argument("--n-features",   type=int,   default=2,     metavar="N")
    p.add_argument("--center-box",   type=float, default=(-10, 10), nargs=2, metavar=("LO", "HI"))
    p.add_argument("--cluster-std",  type=float, default=1.0,   metavar="S")
    p.add_argument("--random-state", type=int,   default=0,     metavar="N")
    p.add_argument("--output",       default="data.dfy",        metavar="FILE")
    return p.parse_args()


def load_blobs(n_samples, k, n_features, center_box, cluster_std, random_state):
    try:
        from sklearn.datasets import make_blobs
    except ImportError:
        sys.exit(
            f"Error: scikit-learn is not installed for this Python interpreter.\n"
            f"Run: {sys.executable} -m pip install scikit-learn"
        )

    X, _ = make_blobs(
        n_samples=n_samples,
        centers=k,
        n_features=n_features,
        center_box=tuple(center_box),
        cluster_std=cluster_std,
        random_state=random_state,
    )
    return X.tolist()


def real_literal(v: float) -> str:
    """Format a Python float as a Dafny real literal."""
    s = f"{v:.10f}"
    s = s.rstrip("0").rstrip(".")
    if "." not in s:
        s += ".0"
    return s


def emit_data(points, k, max_iter, output_path):
    n = len(points)
    d = len(points[0])

    if k > n:
        sys.exit(f"Error: k={k} is larger than the number of points ({n})")

    lines = []

    lines.append("// generated by gen_dafny_test.py — do not edit")
    lines.append(f"// {n} points, {d} dimensions, k={k}, max_iter={max_iter}")
    lines.append("")
    lines.append(f"const K := {k}")
    lines.append(f"const MaxIter := {max_iter}")
    lines.append("")
    lines.append("// MakePoints allocates the dataset used by KMeansTest.dfy.")
    lines.append("// {:verify false} avoids verifying the ensures forall over concrete assignments.")
    lines.append(f"method {{:verify false}} MakePoints() returns (points: array<array<real>>)")
    lines.append(f"  ensures points.Length == {n}")
    lines.append(f"  ensures forall i :: 0 <= i < points.Length ==> points[i].Length == {d}")
    lines.append("{")
    lines.append(f"  points := new array<real>[{n}];")
    for i, pt in enumerate(points):
        coords = ", ".join(real_literal(v) for v in pt)
        lines.append(f"  points[{i}] := new real[{d}][{coords}];")
    lines.append("}")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written {output_path}  ({n} points, {d} dims, k={k}, max_iter={max_iter})")
    print(f"Now run:  dafny run KMeansTest.dfy --allow-warnings")


def main():
    args = parse_args()
    points = load_blobs(
        n_samples=args.n_samples,
        k=args.k,
        n_features=args.n_features,
        center_box=args.center_box,
        cluster_std=args.cluster_std,
        random_state=args.random_state,
    )
    emit_data(points, args.k, args.max_iter, args.output)


if __name__ == "__main__":
    main()
